Added support for 9.4 LTS
ibm-messaging/mq-ansible pull request #112
Opened 2024-08-15 13:11 UTC by marianavillarp

9.4 zip file name now follows the new naming convention (previously only for CD releases). Therefore, naming conventions are not longer defined by type of release (LTS or CD). Instead, latest releases will have the variable `convention` as 'new'.

2024-09-02 12:24 UTC, bimsara-yasitha01 requested changes
Working on Ubuntu 22.04 with the suggested fix, happy to approve when that's pushed:

```
$ dspmqver
Name:        IBM MQ
Version:     9.4.0.0
Level:       p940-L240606.DE
BuildType:   IKAP - (Production)
Platform:    IBM MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 5.15.0-118-generic
O/S Details: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
InstName:    Installation1
InstDesc:    
Primary:     No
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 940
LicenseType: Developer
ReleaseType: Long Term Support (LTS) and Continuous Delivery (CD)
```

2024-09-02 12:24 UTC, bimsara-yasitha01 commented on roles/downloadmq/tasks/main.yml
> +  when: not convention
I got a 'convention is not defined' error here - changing to the below fixed it

```suggestion
  when: convention is undefined
```

2024-09-02 12:31 UTC, bimsara-yasitha01 approved these changes
Looks good, approved!

2024-09-17 10:11 UTC, stewmcl approved these changes
Looking good 👍

2024-09-26 11:58 UTC, merged